[2024-02-09T12:46:26.549+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Danalysis_json_processing_dag.make_post_request_task manual__2024-02-09T12:45:45.856292+00:00 [queued]>
[2024-02-09T12:46:26.618+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Danalysis_json_processing_dag.make_post_request_task manual__2024-02-09T12:45:45.856292+00:00 [queued]>
[2024-02-09T12:46:26.627+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-09T12:46:26.825+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): make_post_request_task> on 2024-02-09 12:45:45.856292+00:00
[2024-02-09T12:46:26.883+0000] {standard_task_runner.py:60} INFO - Started process 82 to run task
[2024-02-09T12:46:26.906+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Danalysis_json_processing_dag', 'make_post_request_task', 'manual__2024-02-09T12:45:45.856292+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/danalysis_dag.py', '--cfg-path', '/tmp/tmp2hmq1m67']
[2024-02-09T12:46:26.931+0000] {standard_task_runner.py:88} INFO - Job 155: Subtask make_post_request_task
[2024-02-09T12:46:27.251+0000] {task_command.py:423} INFO - Running <TaskInstance: Danalysis_json_processing_dag.make_post_request_task manual__2024-02-09T12:45:45.856292+00:00 [running]> on host d3f529db5c6c
[2024-02-09T12:46:27.723+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='amukayoung@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Danalysis_json_processing_dag' AIRFLOW_CTX_TASK_ID='make_post_request_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-09T12:45:45.856292+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-09T12:45:45.856292+00:00'
[2024-02-09T12:46:27.926+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/danalysis_dag.py", line 73, in make_post_request
    response = urllib.request.post(api_endpoint, json=item)
AttributeError: module 'urllib.request' has no attribute 'post'
[2024-02-09T12:46:28.028+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Danalysis_json_processing_dag, task_id=make_post_request_task, execution_date=20240209T124545, start_date=20240209T124626, end_date=20240209T124628
[2024-02-09T12:46:28.100+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 155 for task make_post_request_task (module 'urllib.request' has no attribute 'post'; 82)
[2024-02-09T12:46:28.287+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-09T12:46:28.461+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
