[2024-02-05T20:02:09.982+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Danalysis_json_processing_dag.make_post_request_task manual__2024-02-05T19:51:32.362564+00:00 [queued]>
[2024-02-05T20:02:10.016+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Danalysis_json_processing_dag.make_post_request_task manual__2024-02-05T19:51:32.362564+00:00 [queued]>
[2024-02-05T20:02:10.050+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-02-05T20:02:10.090+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): make_post_request_task> on 2024-02-05 19:51:32.362564+00:00
[2024-02-05T20:02:10.103+0000] {standard_task_runner.py:60} INFO - Started process 121 to run task
[2024-02-05T20:02:10.113+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Danalysis_json_processing_dag', 'make_post_request_task', 'manual__2024-02-05T19:51:32.362564+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/danalysis_dag.py', '--cfg-path', '/tmp/tmpzsu4jxy6']
[2024-02-05T20:02:10.120+0000] {standard_task_runner.py:88} INFO - Job 61: Subtask make_post_request_task
[2024-02-05T20:02:10.232+0000] {task_command.py:423} INFO - Running <TaskInstance: Danalysis_json_processing_dag.make_post_request_task manual__2024-02-05T19:51:32.362564+00:00 [running]> on host d3f529db5c6c
[2024-02-05T20:02:10.368+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='amukayoung@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Danalysis_json_processing_dag' AIRFLOW_CTX_TASK_ID='make_post_request_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T19:51:32.362564+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-05T19:51:32.362564+00:00'
[2024-02-05T20:02:10.377+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: make_post_request() missing 1 required positional argument: 'extracted_data'
[2024-02-05T20:02:10.392+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Danalysis_json_processing_dag, task_id=make_post_request_task, execution_date=20240205T195132, start_date=20240205T200209, end_date=20240205T200210
[2024-02-05T20:02:10.434+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 61 for task make_post_request_task (make_post_request() missing 1 required positional argument: 'extracted_data'; 121)
[2024-02-05T20:02:10.489+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-05T20:02:10.565+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
